export const RESET_COUNTDOWN = 'RESET_COUNTDOWN';
export const START_COUNTDOWN = 'START_COUNTDOWN';
export const STOP_COUNTDOWN = 'STOP_COUNTDOWN';
export const UPDATE_COUNT_VALUE = 'UPDATE_COUNT_VALUE';
export const UPDATE_TIMER = 'UPDATE_TIMER';